export let SERIES_STATUS = {
    DELETE: "DELETE", 
    NOT_DELETED: "NOT DELETED", 
    BACKUP_START: "BACKUP START", 
    BACKUP_DONE: "BACKUP DONE", 
    UPLOAD_START: "UPLOAD START", 
    UPLOAD_FAILED: "UPLOAD FAILED", 
    UPLOAD_SUCCESS: "UPLOAD SUCCESS", 
    UPLOAD_PENDING: "UPLOAD PENDING"
}

export let JOB_STATUS = {
    SUCCESS_STATUS: "Success", 
    RUNNING_STATUS: "Running", 
    FAILED_STATUS: "Failure", 
    CANCELLED_STATUS: "Canceled"
}

export let JOB_TYPE = {
    ARCHIVE_TYPE : "Archive", 
    CLOUDPEER_STORE_TYPE: "OrthancPeerStore"
}